INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('contact_status', 'prospect_a_contacter', 'Prospect à contacter', '#94A3B8', 0, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('contact_status', 'premier_echange', 'Premier échange', '#60A5FA', 1, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('contact_status', 'a_relancer', 'À relancer', '#FBBF24', 2, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('contact_status', 'rex_a_organiser', 'REX à organiser', '#A78BFA', 3, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('contact_status', 'opportunite_identifiee', 'Opportunité identifiée', '#34D399', 4, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('contact_status', 'client_actif', 'Client actif', '#10B981', 5, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('contact_status', 'sans_besoin_actuellement', 'Sans besoin actuellement', '#CBD5E1', 6, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('contact_status', 'inactif', 'Inactif', '#94A3B8', 7, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('contact_status', 'archive', 'Archivé', '#64748B', 8, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('candidat_status', 'a_contacter', 'À contacter', '#94A3B8', 0, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('candidat_status', 'contacte', 'Contacté', '#60A5FA', 1, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('candidat_status', 'qualifie', 'Qualifié', '#38BDF8', 2, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('candidat_status', 'disponible', 'Disponible', '#10B981', 3, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('candidat_status', 'prochainement_disponible', 'Prochainement disponible', '#34D399', 4, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('candidat_status', 'positionne', 'Positionné', '#A78BFA', 5, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('candidat_status', 'en_entretien', 'En entretien', '#FBBF24', 6, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('candidat_status', 'retenu', 'Retenu', '#22C55E', 7, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('candidat_status', 'en_mission', 'En mission', '#0EA5E9', 8, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('candidat_status', 'non_retenu', 'Non retenu', '#F87171', 9, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('candidat_status', 'archive', 'Archivé', '#64748B', 10, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('besoin_status', 'lead_a_qualifier', 'Lead à qualifier', '#94A3B8', 0, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('besoin_status', 'besoin_potentiel', 'Besoin potentiel', '#60A5FA', 1, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('besoin_status', 'besoin_confirme', 'Besoin confirmé', '#38BDF8', 2, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('besoin_status', 'recherche_en_cours', 'Recherche en cours', '#FBBF24', 3, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('besoin_status', 'candidats_positionnes', 'Candidats positionnés', '#A78BFA', 4, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('besoin_status', 'entretiens_en_cours', 'Entretiens en cours', '#F59E0B', 5, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('besoin_status', 'candidat_retenu', 'Candidat retenu', '#22C55E', 6, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('besoin_status', 'gagne', 'Gagné', '#10B981', 7, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('besoin_status', 'perdu', 'Perdu', '#F87171', 8, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('besoin_status', 'suspendu', 'Suspendu', '#CBD5E1', 9, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('besoin_status', 'cloture', 'Clôturé', '#64748B', 10, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('positionnement_status', 'a_etudier', 'À étudier', '#94A3B8', 0, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('positionnement_status', 'a_presenter', 'À présenter', '#60A5FA', 1, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('positionnement_status', 'presente_au_client', 'Présenté au client', '#38BDF8', 2, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('positionnement_status', 'entretien_planifie', 'Entretien planifié', '#FBBF24', 3, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('positionnement_status', 'entretien_realise', 'Entretien réalisé', '#F59E0B', 4, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('positionnement_status', 'en_attente_retour', 'En attente de retour', '#A78BFA', 5, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('positionnement_status', 'retenu', 'Retenu', '#22C55E', 6, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('positionnement_status', 'refuse', 'Refusé', '#F87171', 7, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('positionnement_status', 'desiste', 'Désisté', '#94A3B8', 8, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('echange_type', 'appel', 'Appel', '#60A5FA', 0, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('echange_type', 'email', 'E-mail', '#34D399', 1, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('echange_type', 'linkedin', 'LinkedIn', '#0EA5E9', 2, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('echange_type', 'reunion', 'Réunion', '#A78BFA', 3, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('echange_type', 'visio', 'Visioconférence', '#FBBF24', 4, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('echange_type', 'autre', 'Autre', '#94A3B8', 5, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('besoin_priorite', 'basse', 'Basse', '#94A3B8', 0, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('besoin_priorite', 'normale', 'Normale', '#60A5FA', 1, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('besoin_priorite', 'haute', 'Haute', '#FBBF24', 2, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('besoin_priorite', 'urgente', 'Urgente', '#F87171', 3, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('tech_category', 'cloud', 'Cloud', '#0EA5E9', 0, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('tech_category', 'data_platforms', 'Data Platforms', '#6366F1', 1, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('tech_category', 'data_engineering', 'Data Engineering', '#8B5CF6', 2, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('tech_category', 'business_intelligence', 'Business Intelligence', '#EC4899', 3, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('tech_category', 'etl', 'ETL', '#F59E0B', 4, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('tech_category', 'ia', 'Intelligence Artificielle', '#10B981', 5, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('tech_category', 'devops', 'DevOps', '#64748B', 6, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('tech_category', 'langages', 'Langages & Frameworks', '#22C55E', 7, true) ON CONFLICT (category, value) DO NOTHING;
INSERT INTO pick_lists (category, value, label, color, sort_order, active) VALUES ('tech_category', 'autre', 'Autre', '#94A3B8', 8, true) ON CONFLICT (category, value) DO NOTHING;
